on: 
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build:
    name: Build (${{inputs.os}})
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.16.5

      - uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.os}}
          path: ./wheelhouse/*.whl

  test:
    name: Test (${{inputs.os}}, py${{matrix.python}})
    needs: [build]
    runs-on: ${{inputs.os}}

    permissions:
        contents: read
        actions: read
        checks: write

    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Download built wheel
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.os}}

      - name: Install wheel
        run: python -m pip install --find-links=. Basilisk[test]

      # XXX: Run all the pytests using `-n auto` to split up the tests across
      # different processes. Besides hopefully making things faster, this also
      # seemingly avoids some crashes potentially due to running out of memory.

      - name: Run unit tests
        run: python -m pytest src -v -n auto -m "not scenarioTest" --junitxml=./reports/pytest-unit-results-${{inputs.os}}-py${{matrix.python}}.xml

      - name: Run scenario tests
        run: python -m pytest src -v -n auto -m "scenarioTest" --junitxml=./reports/pytest-scenario-results-${{inputs.os}}-py${{matrix.python}}.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results (${{inputs.os}}, py${{matrix.python}})
          path: reports/*.xml
          reporter: java-junit
          list-tests: failed
          only-summary: true